name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'farid'
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: build
          build-root-directory: app
          gradle-version: 8.7
      - run: ./gradlew checkstyleMain
      - run: ./gradlew test
